global:
  domain:           'asterisk.service.consul'
  #domain:           'sip.target.system'
  domain_wss:       'sip.target.system:8089'

  main_number: '15555550000'

  pcmu_priority: 249
  pcma_priority: 250
  opus_priority: 248

  # Values to test udp+rtp (unencrypted)
  transport:        'udp'
  srtp:             ''
  dtls:             ''

  # Values to test tls+mandatory srtp
  # transport:        'tls'
  # srtp:             'sdes,force'
  # dtls:             'dtls,force'

  play_file:        '/voice_ref_files/8000_2m30.wav'
  play_file_2:      '/voice_ref_files/test01_20s.wav'
  asterisk_context: 'company_users'
  stun_address:     'public.stun.server:3478'

  # Number to dial to reach a service that will answer immediately and echo back RTP
  # Note that any destination that answers and sends RTP is sufficient
  echo_service:     '11111'

  # Time, in milliseconds, to wait for call to answer. 
  # Default time: 30
  pause_after_call: '30000'
databases:
  'sippproxydb':
    type:       'mysql'
    user:       'sipproxyremote'
    password:   'sipproxyremotepass'
    base:       'sipproxy'
    host:       'sipproxy.local'
  'astdb':
    type:       'mysql'
    user:       'asterisk'
    password:   'asteriskpass'
    base:       'asterisk'
    host:       'asterisk.local'
  'astdb_users':
    type:       'mysql'
    user:       'asterisk'
    password:   'asteriskpass'
    base:       'userids'
    host:       'asterisk.local'
accounts:
  # Alice - Used in most scenarios
  'alice':
    # Default auth username, user portion of to header
    username: '101'

    # Extension to dial to reach this device(if different than username )
    #  Default value is username field if this isn't set
    # extension: '##101'

    # Password used to authenticate
    password: 'SuperSecretPass'

    # Auth domain / realm
    # Default: value from global domain config value
    # domain: 'registrar.service.consul'

    # Set this if the username is different than the auth username.
    # Default: value from username field
    # auth_username: '101'

  'bob':
    # This value has to be regex friendly, so escaping + and others is important
    callerid: '[+]123456102'
    username: '102'
    password: 'SuperSecretPass'

  # Has server side call forwarding to user alice
  'carol':
    username: '103'
    password: 'SuperSecretPass'

  # Has server side call forwarding to user carol who forwards to alice
  'carlos':
    username: '104'

  'chuck':
    username: '105'
    password: 'SuperSecretPass'

  # Queue used in test 8, 11, should dial queue with only Alice in it
  'queue08':
    username: '108'

  # Queue used in test 9, should dial queue with only Carol and ignore her call forwarding
  'queue09':
    username: '109'

  # Queue used in test 10, should have single member with it's the same number
  'queue10':
    username: '110'

  # User used in test 10, should be only member of queue10
  'user10':
    username: '110'
    password: 'SuperSecretPass'

  # Queue used in test 11, should have single member, Alice. This queue forwards to a Queue with only Bob as a member
  'queue11':
    username: '111'





